apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-config
  namespace: koordinator-system
data:
  yarn-site.xml: |
    <configuration>
        <property>
            <name>yarn.resourcemanager.admin.address</name>
            <value>0.0.0.0:8033</value>
        </property>
    </configuration>
  core-site.xml: |
    <configuration>
    </configuration>